[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/health/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 --workers 2 --threads 4 chrisb_blog.wsgi:application"
